language: ruby
rvm:
  - 2.2.0
services:
  - redis
cache:
  - bundler
script:
  - bundle exec rspec
env:
    REDIS_URL=redis://localhost
    ROUTEMASTER_URL=https://routemaster.dev/
    ROUTEMASTER_CLIENT_UUID=demo
    ROUTEMASTER_CALLBACK_UUID=demo
    ROUTEMASTER_CALLBACK_PATH=/events
    ROUTEMASTER_DRAIN_TOKENS=demo
    ROUTEMASTER_SUBSCRIBER_TIMEOUT=6000
    APP_URL=https://routemaster-timemachine.dev
